import { query } from '../database/db.js';
import { FISH_TABLE } from '../config/fishRarities.js';
const COOLDOWNS = { daily: 86400000, work: 1800000, fish: 1000 };
async function ensure(userId) { await query('INSERT INTO economy_users (user_id) VALUES ($1) ON CONFLICT DO NOTHING', [userId]); return (await query('SELECT * FROM economy_users WHERE user_id=$1', [userId])).rows[0]; }
export async function balance(userId) { return ensure(userId); }
export async function cooldownRemaining(userId,type) { const user=await ensure(userId); const field=`last_${type}`; const last=user[field]?new Date(user[field]).getTime():0; return Math.max(0,(COOLDOWNS[type]||0)-(Date.now()-last)); }
export async function addMoney(userId, amount, type = 'admin') { if (!Number.isSafeInteger(amount) || amount === 0) throw new Error('Amount must be a safe non-zero integer.'); await ensure(userId); await query('UPDATE economy_users SET wallet=wallet+$1, updated_at=NOW() WHERE user_id=$2 AND wallet+$1>=0', [amount, userId]); await query('INSERT INTO economy_transactions (user_id,type,amount) VALUES ($1,$2,$3)', [userId,type,amount]); return balance(userId); }
export async function claim(userId, type) { const user = await ensure(userId); const field = `last_${type}`; const last = user[field] ? new Date(user[field]).getTime() : 0; const remaining = COOLDOWNS[type] - (Date.now() - last); if (remaining > 0) throw new Error(`Please wait ${Math.ceil(remaining / 1000)} second(s).`); const amount = type === 'daily' ? 1000 : type === 'work' ? 250 + Math.floor(Math.random() * 751) : 100 + Math.floor(Math.random() * 401); await query(`UPDATE economy_users SET wallet=wallet+$1, ${field}=NOW(), updated_at=NOW() WHERE user_id=$2`, [amount, userId]); await query('INSERT INTO economy_transactions (user_id,type,amount) VALUES ($1,$2,$3)', [userId,type,amount]); return { amount, ...(await balance(userId)) }; }
export async function transfer(fromId,toId,amount) { if(fromId===toId||amount<1) throw new Error('Choose another user and a positive amount.'); await ensure(fromId); await ensure(toId); const c=await query('UPDATE economy_users SET wallet=wallet-$1 WHERE user_id=$2 AND wallet >= $1',[amount,fromId]); if(!c.rowCount) throw new Error('Insufficient wallet funds.'); await query('UPDATE economy_users SET wallet=wallet+$1 WHERE user_id=$2',[amount,toId]); await query('INSERT INTO economy_transactions (user_id,type,amount,metadata) VALUES ($1,$2,$3,$4),($5,$6,$7,$8)',[fromId,'transfer_out',-amount,JSON.stringify({toId}),toId,'transfer_in',amount,JSON.stringify({fromId})]); return balance(fromId); }
export async function bankMove(userId,amount,direction) { if(amount<1) throw new Error('Amount must be positive.'); const u=await ensure(userId); if(direction==='deposit'&&u.wallet<amount) throw new Error('Insufficient wallet funds.'); if(direction==='withdraw'&&u.bank<amount) throw new Error('Insufficient bank funds.'); const delta=direction==='deposit'?[ -amount, amount ]:[ amount,-amount ]; await query('UPDATE economy_users SET wallet=wallet+$1,bank=bank+$2 WHERE user_id=$3',[delta[0],delta[1],userId]); return balance(userId); }
export async function leaderboard(limit=10) { return (await query('SELECT user_id,wallet,bank,(wallet+bank) AS total FROM economy_users ORDER BY total DESC LIMIT $1',[limit])).rows; }
export function rollFish({ luckBonus = 0 } = {}) {
  const rarityLuck = { common: -0.35, uncommon: -0.2, rare: 0, epic: 0.1, legendary: 0.2, mythic: 0.3, ancient: 0.45, celestial: 0.65, secret: 0.9, tsukuyomi: 1.2 };
  const luck = Math.max(0, Number(luckBonus) || 0) / 100;
  const weighted = FISH_TABLE.map(fish => ({ fish, weight: fish.weight * Math.max(0.08, 1 + luck * (rarityLuck[fish.rarity] ?? 0)) }));
  const total = weighted.reduce((sum, entry) => sum + entry.weight, 0);
  let n = Math.random() * total;
  for (const entry of weighted) { n -= entry.weight; if (n <= 0) return entry.fish; }
  return FISH_TABLE[0];
}
export async function saveFish(userId,fish) { const prior=await query('SELECT 1 FROM fish_inventory WHERE user_id=$1 AND fish_name=$2 LIMIT 1',[userId,fish.name]); await query('INSERT INTO fish_catches (user_id,fish_name,rarity,value) VALUES ($1,$2,$3,$4)',[userId,fish.name,fish.rarity,fish.value]); await query('INSERT INTO fish_inventory (user_id,fish_name,rarity,quantity) VALUES ($1,$2,$3,1) ON CONFLICT (user_id,fish_name) DO UPDATE SET quantity=fish_inventory.quantity+1',[userId,fish.name,fish.rarity]); return { isNew: prior.rowCount===0 }; }
export async function fishPointsLeaderboard(limit=10) { return (await query(`SELECT user_id, SUM(CASE rarity WHEN 'common' THEN 1 WHEN 'secret' THEN 70 WHEN 'tsukuyomi' THEN 100 ELSE 0 END)::BIGINT AS points, COUNT(*)::BIGINT AS catches FROM fish_catches GROUP BY user_id HAVING COUNT(*)>0 ORDER BY points DESC,user_id ASC LIMIT $1`,[limit])).rows; }
export async function fishInventory(userId) { return (await query('SELECT fish_name,rarity,quantity FROM fish_inventory WHERE user_id=$1 ORDER BY quantity DESC,fish_name',[userId])).rows; }
export async function fishAlmanac(userId) { return (await query('SELECT rarity,COUNT(*)::int AS caught,COUNT(DISTINCT fish_name)::int AS discovered FROM fish_catches WHERE user_id=$1 GROUP BY rarity ORDER BY discovered DESC',[userId])).rows; }
export async function fishCollection(userId) { const owned=await fishInventory(userId); const counts=new Map(owned.map(row=>[row.fish_name,Number(row.quantity)])); return FISH_TABLE.map(fish=>({...fish,quantity:counts.get(fish.name)||0})); }

export async function castFish(userId) { const user = await ensure(userId); const last = user.last_fish ? new Date(user.last_fish).getTime() : 0; const remaining = COOLDOWNS.fish - (Date.now() - last); if (remaining > 0) throw new Error('Please wait ' + Math.ceil(remaining / 1000) + ' second(s).'); await query('UPDATE economy_users SET last_fish=NOW(), updated_at=NOW() WHERE user_id=$1',[userId]); return balance(userId); }
