import { query } from '../database/db.js';

const TRUTH_PROMPTS = [
  '[PG] WHO: Which friend can tell you are stressed before you say anything, and what do they notice?',
  '[PG] WHO: Who taught you a small habit you still use today?',
  '[PG] WHO: Who would you choose to plan a last-minute day out with, and why?',
  '[PG] WHO: Who made you laugh the hardest this month, and what happened?',
  '[PG] WHO: Who would you ask to give an honest opinion on your latest idea?',
  '[PG] WHERE: Where in your town or city would you take a new friend for one hour?',
  '[PG] WHERE: Where do you go online when you want to learn something useful?',
  '[PG] WHERE: Where do you feel most like yourself: at home, school/work, outside, or online?',
  '[PG] WHERE: Where would your ideal quiet weekend start?',
  '[PG] WHERE: Where is one place you want to revisit because of a good memory?',
  '[PG] WHEN: When did you last surprise yourself by doing something well?',
  '[PG] WHEN: When are you at your most productive during a normal day?',
  '[PG] WHEN: When did you first realize a hobby was more than a passing interest?',
  '[PG] WHEN: When do you know you need to take a break from your phone?',
  '[PG] WHEN: When was the last time a song changed your mood immediately?',
  '[PG] WHAT: What is a tiny thing that instantly makes your day better?',
  '[PG] WHAT: What is one skill you have that people would not guess at first?',
  '[PG] WHAT: What is your most specific comfort food or drink order?',
  '[PG] WHAT: What game, movie, book, or series could you talk about for ten minutes without preparing?',
  '[PG] WHAT: What would be on a playlist called “this is so me”?',
  '[PG] HOW: How do you usually celebrate a small win?',
  '[PG] HOW: How would a close friend describe your best quality?',
  '[PG] HOW: How do you get yourself moving when you have no motivation?',
  '[PG] HOW: How did you choose your current favorite hobby?',
  '[PG] HOW: How would you make a new member feel included in a group chat?',
  '[PG-13] WHO: Who do you find easiest to apologize to, and what makes it easier?',
  '[PG-13] WHO: Who has given you advice you did not like at first but later understood?',
  '[PG-13] WHO: Who brings out your calm side, and who brings out your chaotic side?',
  '[PG-13] WHO: Who would you trust with a difficult decision, and what quality earned that trust?',
  '[PG-13] WHO: Who do you wish you thanked more often for something small?',
  '[PG-13] WHERE: Where do you go when you need privacy without completely isolating yourself?',
  '[PG-13] WHERE: Where do you feel the most pressure to act like a different version of yourself?',
  '[PG-13] WHERE: Where have you had a conversation that changed your perspective?',
  '[PG-13] WHERE: Where would you go for one day if you needed a fresh start?',
  '[PG-13] WHERE: Where do you draw the line between being helpful and overextending yourself?',
  '[PG-13] WHEN: When was the last time you changed your mind after hearing someone out?',
  '[PG-13] WHEN: When do you notice that you are avoiding a task or conversation?',
  '[PG-13] WHEN: When did you learn that a friendship needed clearer boundaries?',
  '[PG-13] WHEN: When are you most likely to overthink, and what helps you reset?',
  '[PG-13] WHEN: When did you last choose the harder but more honest option?',
  '[PG-13] WHAT: What is a harmless “red flag” you have, such as being late, overthinking, or replying slowly?',
  '[PG-13] WHAT: What is one boundary you learned you need in friendships?',
  '[PG-13] WHAT: What kind of compliment do you remember for a long time?',
  '[PG-13] WHAT: What is a mistake that taught you a useful lesson without naming anyone involved?',
  '[PG-13] WHAT: What topic could you discuss respectfully even when you strongly disagree?',
  '[PG-13] HOW: How do you react when you feel left out of a conversation?',
  '[PG-13] HOW: How do you tell the difference between a bad day and a problem that needs attention?',
  '[PG-13] HOW: How would you explain your personal definition of loyalty?',
  '[PG-13] HOW: How do you want friends to tell you when you have hurt their feelings?',
  '[PG-13] HOW: How have you become different from the person you were two years ago?'
];

const DARE_PROMPTS = [
  '[PG] Make a five-song mini playlist for a rainy-day bus ride; list only the titles and artists.',
  '[PG] Describe your ideal café order and seat as if you are reviewing it for a magazine.',
  '[PG] Give one member-safe recommendation for a movie, series, game, or book and explain it in two sentences.',
  '[PG] Write a three-line pep talk for someone having a very ordinary bad day.',
  '[PG] Create a group-chat nickname for yourself based on your favorite food or hobby.',
  '[PG] Tell a harmless childhood story that still makes you laugh.',
  '[PG] Post your top three snacks for a late-night study or gaming session.',
  '[PG] Write a tiny travel postcard from a place you want to visit.',
  '[PG] Give a fictional character a job they would be unexpectedly good at.',
  '[PG] Describe your current mood using only weather words.',
  '[PG] Share one useful life shortcut you actually use.',
  '[PG] Make a two-sentence trailer voice-over for your week so far.',
  '[PG] Write a kind but very specific compliment someone could give a friend.',
  '[PG] Pick a song for “walking home after a good day” and say why it fits.',
  '[PG] Invent a harmless challenge for the next person, such as naming a comfort food.',
  '[PG] Explain your favorite hobby to someone who has never heard of it in one sentence.',
  '[PG] Make a ranking of three fictional places you would visit for exactly one day.',
  '[PG] Write a dramatic headline about the last snack or meal you ate.',
  '[PG] Share a photo-free “starter pack” of five things that represent your week.',
  '[PG] Give the chat one question that helps people discover a shared interest.',
  '[PG] Tell a short story using these words: key, rain, message, and midnight.',
  '[PG] Invent a new holiday and explain the one tradition everyone must follow.',
  '[PG] Give a very serious review of an everyday object near you.',
  '[PG] Share one small goal for this week and one realistic first step.',
  '[PG] Turn your favorite drink into a fictional character with a name and personality.',
  '[PG-13] Share a harmless unpopular opinion and defend it without insulting the other side.',
  '[PG-13] Describe your most harmless personal “red flag” in one funny sentence.',
  '[PG-13] Tell an awkward-but-safe moment that you can laugh about now; do not name anyone else.',
  '[PG-13] Write a boundary you think more friendships should normalize.',
  '[PG-13] Give advice to your past self from one year ago in exactly two sentences.',
  '[PG-13] Finish this honestly: “I feel most confident when I…”',
  '[PG-13] Finish this honestly: “A small thing that drains my energy is…”',
  '[PG-13] Name one quality that makes someone feel safe to talk to.',
  '[PG-13] Write a respectful message you could send after a misunderstanding with a friend.',
  '[PG-13] Share a habit you are trying to improve and one strategy that might help.',
  '[PG-13] Write a “not today” note for one unhelpful thought, without sharing private details.',
  '[PG-13] Explain one sign that tells you a group conversation is becoming uncomfortable.',
  '[PG-13] Give a short example of how to disagree without turning it into an argument.',
  '[PG-13] Write three words you want people to associate with you.',
  '[PG-13] Share a lesson you learned from a friendship, without identifying anyone.',
  '[PG-13] Make a “future me will thank me” checklist with three small items.',
  '[PG-13] Say one thing you are better at now than you were last year.',
  '[PG-13] Write a respectful response to someone cancelling plans at the last minute.',
  '[PG-13] Describe a healthy way you reset after an argument or stressful conversation.',
  '[PG-13] Give one example of a compliment that praises effort rather than appearance.',
  '[PG-13] Write the first line of a journal entry titled “A better week starts with…”',
  '[PG-13] Name a conversation topic that brings people together in your experience.',
  '[PG-13] Describe a time you changed your opinion without naming the people involved.',
  '[PG-13] Write a one-sentence promise you want to keep to yourself this month.',
  '[PG-13] Give a friend a gentle reminder they might need to hear today.'
];

const FAVORITE_TRUTHS = [
  '[PG] WHAT: What is your favorite snack combination that other people might find unusual?',
  '[PG] WHAT: What is your favorite song right now, and which exact part makes you replay it?',
  '[PG] WHAT: What is your favorite fictional character’s most relatable trait?',
  '[PG] WHAT: What is your favorite color to wear, and what mood does it give you?',
  '[PG] WHAT: What is your favorite game to play with friends rather than alone?',
  '[PG] WHAT: What is your favorite movie, series, anime, or book scene without giving spoilers?',
  '[PG] WHAT: What is your favorite seasonal weather, and what would your perfect day in it look like?',
  '[PG] WHAT: What is your favorite comfort item in your room or bag?',
  '[PG] WHAT: What is your favorite smell, and what memory does it connect to?',
  '[PG] WHAT: What is your favorite kind of compliment to receive?',
  '[PG] WHAT: What is your favorite thing to order when you want to treat yourself?',
  '[PG] WHAT: What is your favorite emoji, emoticon, or reaction to use and why?',
  '[PG] WHAT: What is your favorite school or work task when you are in the mood to be productive?',
  '[PG] WHAT: What is your favorite way to spend an hour with no plans?',
  '[PG] WHAT: What is your favorite small tradition with friends or family?',
  '[PG] WHAT: What is your favorite thing about your current hobby?',
  '[PG] WHAT: What is your favorite kind of gift to give someone?',
  '[PG] WHAT: What is your favorite internet rabbit hole or topic to learn about?',
  '[PG] WHAT: What is your favorite outfit detail: shoes, jewelry, hoodie, bag, or something else?',
  '[PG] WHAT: What is your favorite way to make a boring day feel less boring?',
  '[PG] WHO: Who would understand your taste in music best, and what would you play for them first?',
  '[PG] WHO: Who would you trust to choose a restaurant or snack for you?',
  '[PG] WHERE: Where would you go for your ideal low-budget hangout?',
  '[PG] WHERE: Where do you find your best recommendations for games, songs, or shows?',
  '[PG] WHEN: When do you most enjoy listening to music: commuting, studying, late at night, or another time?',
  '[PG] WHEN: When did you last discover a favorite artist, game, or series?',
  '[PG] HOW: How do you decide whether a new song, game, or show becomes a favorite?',
  '[PG] HOW: How would you introduce your favorite hobby to a curious beginner?',
  '[PG-13] WHAT: What opinion about a popular food, show, game, or trend do you defend every time?',
  '[PG-13] WHAT: What is a favorite of yours that you used to hide because you worried it was uncool?',
  '[PG-13] WHAT: What kind of people, conversations, or spaces make you feel most comfortable?',
  '[PG-13] WHAT: What is one interest you want to explore more this year?',
  '[PG-13] WHAT: What is a harmless pet peeve that can instantly test your patience?',
  '[PG-13] WHAT: What is one personal value you want your friends to notice about you?',
  '[PG-13] WHO: Who has influenced your taste in music, fashion, games, or food the most?',
  '[PG-13] WHERE: Where do you go when you need inspiration for a creative idea?',
  '[PG-13] WHEN: When do you feel most confident being yourself?',
  '[PG-13] WHEN: When did a hobby or fandom help you connect with someone new?',
  '[PG-13] HOW: How do you react when someone dislikes something you genuinely love?',
  '[PG-13] HOW: How do you tell a friend you need quiet time without making them feel rejected?',
  '[PG] WHAT: What fictional world would fit your personality best, and what would you do there first?',
  '[PG] WHAT: What is the best meal you can make or want to learn to make?',
  '[PG] WHAT: What is your go-to topic when you want to start a fun conversation?',
  '[PG] WHAT: What is one tiny luxury you enjoy more than most people do?',
  '[PG] WHERE: Where would you take someone visiting your city for the first time?',
  '[PG] WHEN: When are you most likely to try a new food, song, game, or activity?',
  '[PG] HOW: How do you recharge after spending a lot of time around people?',
  '[PG-13] WHAT: What interest of yours has changed the most in the last two years?',
  '[PG-13] WHO: Who would you call for a recommendation when you cannot choose what to watch or play?',
  '[PG-13] HOW: How would you describe your sense of humor to someone new?'
];

const FAVORITE_DARES = [
  '[PG] Make a top-five list of your favorite snacks and give each one a tiny award title.',
  '[PG] Share a three-item starter pack for someone who wants to understand your taste in music.',
  '[PG] Recommend one game, show, anime, book, or movie and describe its vibe without spoilers.',
  '[PG] Describe your favorite drink as if it is a famous celebrity being interviewed.',
  '[PG] Create a mini menu with three foods that represent your personality.',
  '[PG] Write a two-line review of your current favorite song without naming its lyrics.',
  '[PG] Name three fictional characters you would invite to a calm dinner and assign each a seat.',
  '[PG] Give your favorite color a personality, hobby, and one dramatic secret.',
  '[PG] Make a five-word slogan for your favorite hobby.',
  '[PG] Build a one-day itinerary around your favorite kind of weather.',
  '[PG] Share your ideal study, gaming, or relaxing setup using exactly five items.',
  '[PG] Create a silly award for the best food you ate recently and explain the winner.',
  '[PG] Write a tiny postcard from your dream travel destination.',
  '[PG] Rank three comfort foods from “good” to “would defend forever.”',
  '[PG] Turn your favorite animal into a Discord username and status.',
  '[PG] Give the chat a one-sentence recommendation based on your favorite genre.',
  '[PG] Describe a favorite memory using only three emojis and one sentence.',
  '[PG] Invent a themed café based on your favorite game, show, or hobby.',
  '[PG] Share a “listen to this when…” recommendation for one mood.',
  '[PG] Make a two-question quiz that could reveal whether someone shares your taste.',
  '[PG] Tell the group your favorite harmless fun fact and why you remember it.',
  '[PG] Describe your ideal birthday cake, meal, or celebration in two sentences.',
  '[PG] Create a playlist title for your current week and list three song vibes, not lyrics.',
  '[PG] Write a friendly invitation to try one of your favorite activities.',
  '[PG] Pick a favorite fictional place and explain the first rule you would make there.',
  '[PG] Name a favorite item you own and give it an overly dramatic product advertisement.',
  '[PG] Make a “things I will always say yes to” list with three safe answers.',
  '[PG] Give a movie or game genre a new funny name based on its usual plot.',
  '[PG] Describe your perfect weekend morning without mentioning a screen.',
  '[PG] Choose one favorite song, food, and color to represent your mood today.',
  '[PG-13] Share one harmless unpopular favorite and explain it respectfully in two sentences.',
  '[PG-13] Write a polite defense for something people often call overrated.',
  '[PG-13] Describe your personal “do not disturb” ritual in a way friends could understand.',
  '[PG-13] Make a short list of three conversation topics that always make you light up.',
  '[PG-13] Write a gentle boundary around one hobby, interest, or free-time need.',
  '[PG-13] Give a respectful “not for me, but I see the appeal” review of a popular trend.',
  '[PG-13] Share one interest you want to try and one small first step you could take.',
  '[PG-13] Write a note to your future self about making room for the things you enjoy.',
  '[PG-13] Make a “my energy is low, but I still care” message a friend could understand.',
  '[PG-13] Explain how a friend can invite you somewhere in a way that feels comfortable.',
  '[PG] Make a fictional mascot for your favorite food, drink, or hobby.',
  '[PG] Give three objects near you a rating based on how well they match your personality.',
  '[PG] Create a tiny bucket list of three fun experiences related to your interests.',
  '[PG] Write a haiku about a food, game, place, or song you love.',
  '[PG] Name a favorite comfort activity and give someone a beginner-friendly first step.',
  '[PG] Invent a sticker pack based on your favorite things; name its first three stickers.',
  '[PG] Make a five-word review for your favorite season.',
  '[PG-13] Write a short “I changed my mind about this” post about a harmless taste or interest.',
  '[PG-13] Give a specific, kind compliment to someone who shares one of your interests.',
  '[PG-13] Describe a hobby you admire in others even if you are not good at it.'
];

const PROMPT_VARIATIONS = [
  'Give one real example if you can.',
  'Keep it honest and concise.',
  'You may answer in any language.',
  'Use a detail that makes your answer personal.',
  'A short answer is completely fine.',
  'Do not name anyone who would not want to be named.',
  'Make it something the group can understand.',
  'Say what you genuinely think, not what sounds impressive.',
  'Keep other people’s private information private.',
  'Add one detail that helps people get to know you.'
];

function buildPromptPool(prompts) {
  return Object.freeze(prompts.flatMap(prompt => PROMPT_VARIATIONS.map(variation => `${prompt}\n*${variation}*`)));
}

export const SAFE_TRUTHS = buildPromptPool([...TRUTH_PROMPTS, ...FAVORITE_TRUTHS]);
export const SAFE_DARES = buildPromptPool([...DARE_PROMPTS, ...FAVORITE_DARES]);
let settingsReady=false;
async function ensureSettingsTable() {
  if(settingsReady) return;
  await query(`CREATE TABLE IF NOT EXISTS truth_or_dare_settings (
    guild_id TEXT PRIMARY KEY, channel_id TEXT NOT NULL, panel_message_id TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`);
  settingsReady=true;
}

export function randomTruthOrDare(type) {
  const list=type==='dare' ? SAFE_DARES : SAFE_TRUTHS;
  return list[Math.floor(Math.random()*list.length)];
}

export async function saveTruthOrDareSettings(guildId, channelId) {
  await ensureSettingsTable();
  await query(`INSERT INTO truth_or_dare_settings (guild_id,channel_id) VALUES ($1,$2)
    ON CONFLICT (guild_id) DO UPDATE SET channel_id=EXCLUDED.channel_id,updated_at=NOW()`,[guildId,channelId]);
}
export async function getTruthOrDareSettings(guildId) { await ensureSettingsTable(); return (await query('SELECT * FROM truth_or_dare_settings WHERE guild_id=$1',[guildId])).rows[0] ?? null; }
export async function saveTruthOrDarePanel(guildId,messageId) { await ensureSettingsTable(); await query('UPDATE truth_or_dare_settings SET panel_message_id=$2,updated_at=NOW() WHERE guild_id=$1',[guildId,messageId]); }
