import { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } from 'discord.js';
import { balance, claim, addMoney } from './services/economyService.js';
import { setLogChannel, ensureGuild } from './services/guildService.js';
import { createCase, warn, recentCases } from './services/moderationService.js';
export const commands = [
  new SlashCommandBuilder().setName('ping').setDescription('Check whether Yachiyo is online.'),
  new SlashCommandBuilder().setName('balance').setDescription('View your global Yachiyo balance.').addUserOption(o=>o.setName('user').setDescription('User to view').setRequired(false)),
  new SlashCommandBuilder().setName('daily').setDescription('Claim your daily cosmic allowance.'),
  new SlashCommandBuilder().setName('work').setDescription('Work for coins.'),
  new SlashCommandBuilder().setName('fish').setDescription('Go fishing for coins.'),
  new SlashCommandBuilder().setName('economy-add').setDescription('Add global coins to a user.').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addUserOption(o=>o.setName('user').setDescription('Target').setRequired(true)).addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true)),
  new SlashCommandBuilder().setName('logs').setDescription('Set the audit-log channel.').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addChannelOption(o=>o.setName('channel').setDescription('Text channel').setRequired(true))
  ,new SlashCommandBuilder().setName('warn').setDescription('Warn a member.').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(false))
  ,new SlashCommandBuilder().setName('warnings').setDescription('View recent warnings and cases.').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true))
  ,new SlashCommandBuilder().setName('kick').setDescription('Kick a member.').setDefaultMemberPermissions(PermissionFlagsBits.KickMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(false))
  ,new SlashCommandBuilder().setName('ban').setDescription('Ban a member.').setDefaultMemberPermissions(PermissionFlagsBits.BanMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(false))
  ,new SlashCommandBuilder().setName('timeout').setDescription('Timeout a member.').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addIntegerOption(o=>o.setName('minutes').setDescription('Minutes, max 28 days').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(false))
  ,new SlashCommandBuilder().setName('purge').setDescription('Delete recent messages.').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addIntegerOption(o=>o.setName('amount').setDescription('1–100').setRequired(true))
].map(c=>c.toJSON());
export async function handleCommand(interaction) {
  await ensureGuild(interaction.guildId);
  const name=interaction.commandName;
  if(name==='ping') return interaction.reply('Yachiyo is watching over this server.');
  if(name==='balance') { const user=interaction.options.getUser('user')??interaction.user; const b=await balance(user.id); return interaction.reply({embeds:[new EmbedBuilder().setColor(0x8e7dff).setTitle('☾ Cosmic Balance').setDescription(`<@${user.id}> has **${b.wallet.toLocaleString()}** coins in their global wallet and **${b.bank.toLocaleString()}** in the bank.`)]}); }
  if(['daily','work','fish'].includes(name)) { try { const r=await claim(interaction.user.id,name); return interaction.reply(`✦ You received **${r.amount.toLocaleString()}** coins.`); } catch(e) { return interaction.reply({content:`Yachiyo says: ${e.message}`,ephemeral:true}); } }
  if(name==='economy-add') { const b=await addMoney(interaction.options.getUser('user').id,interaction.options.getInteger('amount'),'admin'); return interaction.reply(`Added coins. New wallet: **${b.wallet.toLocaleString()}**.`); }
  if(name==='logs') { const channel=interaction.options.getChannel('channel'); await setLogChannel(interaction.guildId,channel.id); return interaction.reply(`Audit logs will be sent to <#${channel.id}>.`); }
  if(['warn','kick','ban','timeout'].includes(name)) { const user=interaction.options.getUser('user'); const reason=interaction.options.getString('reason')||'No reason provided'; const member=await interaction.guild.members.fetch(user.id).catch(()=>null); if(!member) return interaction.reply({content:'That member is not in this server.',ephemeral:true}); try { let duration=null; if(name==='warn') await warn(interaction.guildId,user.id,interaction.user.id,reason); if(name==='kick') { await member.kick(reason); await createCase({guildId:interaction.guildId,targetId:user.id,moderatorId:interaction.user.id,action:'kick',reason}); } if(name==='ban') { await member.ban({reason}); await createCase({guildId:interaction.guildId,targetId:user.id,moderatorId:interaction.user.id,action:'ban',reason}); } if(name==='timeout') { const minutes=interaction.options.getInteger('minutes'); if(minutes<1||minutes>40320) return interaction.reply({content:'Minutes must be between 1 and 40,320.',ephemeral:true}); duration=minutes*60; await member.timeout(minutes*60000,reason); await createCase({guildId:interaction.guildId,targetId:user.id,moderatorId:interaction.user.id,action:'timeout',reason,durationSeconds:duration}); } return interaction.reply(`Yachiyo completed **${name}** for <@${user.id}>. Case recorded.`); } catch(e) { return interaction.reply({content:`I could not complete that action: ${e.message}`,ephemeral:true}); } }
  if(name==='warnings') { const rows=await recentCases(interaction.guildId,interaction.options.getUser('user').id); return interaction.reply({embeds:[new EmbedBuilder().setColor(0xffc857).setTitle('Moderation Cases').setDescription(rows.length?rows.map(x=>`#${x.id} • **${x.action}** • ${x.reason}`).join('\n'):'No cases found.')]}); }
  if(name==='purge') { const amount=interaction.options.getInteger('amount'); if(amount<1||amount>100) return interaction.reply({content:'Amount must be 1–100.',ephemeral:true}); const deleted=await interaction.channel.bulkDelete(amount,true); await createCase({guildId:interaction.guildId,targetId:interaction.user.id,moderatorId:interaction.user.id,action:'purge',reason:`Deleted ${deleted.size} messages`}); return interaction.reply({content:`Deleted ${deleted.size} messages.`,ephemeral:true}); }
}
