import { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle } from 'discord.js';
import { balance, claim, castFish, addMoney, transfer, bankMove, leaderboard, rollFish, saveFish, fishInventory, fishAlmanac, cooldownRemaining } from './services/economyService.js';
import { FISH_RARITIES } from './config/fishRarities.js';
import { createFishCard } from './ui/fishCard.js';
import { runPullSequence } from './services/fishingPresentation.js';
import { setLogChannel, setFishChannel, getFishChannel, ensureGuild } from './services/guildService.js';
import { createCase, warn, recentCases } from './services/moderationService.js';
import { sendAuditLog } from './services/auditService.js';
import { setConfessionChannel } from './services/confessionService.js';
import { getRod, upgradeRod, getActiveEffects, buyItem, drinkItem } from './services/fishingProgression.js';
const YACHIYO_PURPLE = 0x8e7dff;
const YACHIYO_BLUE = 0x4db8e8;
const yEmbed = (title, description, color = YACHIYO_PURPLE) => new EmbedBuilder().setColor(color).setTitle(title).setDescription(description).setFooter({ text: 'Yachiyo • Cosmic server manager' });
export const commands = [
  new SlashCommandBuilder().setName('ping').setDescription('Check whether Yachiyo is online.'),
  new SlashCommandBuilder().setName('help').setDescription('Open Yachiyo’s command center.'),
  new SlashCommandBuilder().setName('balance').setDescription('View your global Yachiyo balance.').addUserOption(o=>o.setName('user').setDescription('User to view').setRequired(false)),
  new SlashCommandBuilder().setName('daily').setDescription('Claim your daily cosmic allowance.'),
  new SlashCommandBuilder().setName('work').setDescription('Work for coins.'),
  new SlashCommandBuilder().setName('fish').setDescription('Go fishing for coins.'),
  new SlashCommandBuilder().setName('economy-add').setDescription('Add global coins to a user.').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addUserOption(o=>o.setName('user').setDescription('Target').setRequired(true)).addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true)),
  new SlashCommandBuilder().setName('logs').setDescription('Set the audit-log channel.').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addChannelOption(o=>o.setName('channel').setDescription('Text channel').setRequired(true))
  ,new SlashCommandBuilder().setName('confession').setDescription('Submit an anonymous confession.').setDMPermission(false)
  ,new SlashCommandBuilder().setName('confession-setup').setDescription('Set the channel where confessions are published.').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).setDMPermission(false).addChannelOption(o=>o.setName('channel').setDescription('Confession channel').setRequired(true))
  ,new SlashCommandBuilder().setName('fish-setup').setDescription('Set the only channel where fishing is allowed.').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).setDMPermission(false).addChannelOption(o=>o.setName('channel').setDescription('Fishing channel').setRequired(true))
  ,new SlashCommandBuilder().setName('warn').setDescription('Warn a member.').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(false))
  ,new SlashCommandBuilder().setName('warnings').setDescription('View recent warnings and cases.').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true))
  ,new SlashCommandBuilder().setName('kick').setDescription('Kick a member.').setDefaultMemberPermissions(PermissionFlagsBits.KickMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(false))
  ,new SlashCommandBuilder().setName('ban').setDescription('Ban a member.').setDefaultMemberPermissions(PermissionFlagsBits.BanMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(false))
  ,new SlashCommandBuilder().setName('timeout').setDescription('Timeout a member.').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addIntegerOption(o=>o.setName('minutes').setDescription('Minutes, max 28 days').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(false))
  ,new SlashCommandBuilder().setName('purge').setDescription('Delete recent messages.').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addIntegerOption(o=>o.setName('amount').setDescription('1–100').setRequired(true))
  ,new SlashCommandBuilder().setName('pay').setDescription('Transfer global coins.').addUserOption(o=>o.setName('user').setDescription('Recipient').setRequired(true)).addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true))
  ,new SlashCommandBuilder().setName('deposit').setDescription('Move coins into your bank.').addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true))
  ,new SlashCommandBuilder().setName('withdraw').setDescription('Withdraw coins from your bank.').addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true))
  ,new SlashCommandBuilder().setName('leaderboard').setDescription('View the global economy leaderboard.')
  ,new SlashCommandBuilder().setName('unlock').setDescription('Unlock the current channel.').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels)
  ,new SlashCommandBuilder().setName('lock').setDescription('Lock the current channel.').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels)
  ,new SlashCommandBuilder().setName('unban').setDescription('Unban a user.').setDefaultMemberPermissions(PermissionFlagsBits.BanMembers).addStringOption(o=>o.setName('user_id').setDescription('User ID').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(false))
  ,new SlashCommandBuilder().setName('untimeout').setDescription('Remove a member timeout.').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true))
  ,new SlashCommandBuilder().setName('fishinventory').setDescription('View your caught fish collection.')
  ,new SlashCommandBuilder().setName('fishalmanac').setDescription('View your fishing discoveries.')
  ,new SlashCommandBuilder().setName('give').setDescription('Give global coins to another user.').addUserOption(o=>o.setName('user').setDescription('Recipient').setRequired(true)).addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true))
  ,new SlashCommandBuilder().setName('gamble').setDescription('Risk coins for a chance at a larger reward.').addIntegerOption(o=>o.setName('amount').setDescription('Amount').setRequired(true)).addStringOption(o=>o.setName('multiplier').setDescription('Choose your risk and reward multiplier.').setRequired(true).addChoices({name:'x1.5 • Safe • 65% chance',value:'1.5'},{name:'x2 • Balanced • 45% chance',value:'2'},{name:'x3 • Risky • 25% chance',value:'3'}))
  ,new SlashCommandBuilder().setName('rob').setDescription('Attempt to rob another user.').addUserOption(o=>o.setName('user').setDescription('Target').setRequired(true))
  ,new SlashCommandBuilder().setName('fishprofile').setDescription('View a global fishing profile.').addUserOption(o=>o.setName('user').setDescription('User').setRequired(false))
  ,new SlashCommandBuilder().setName('fishleaderboard').setDescription('View the global fishing leaderboard.')
  ,new SlashCommandBuilder().setName('fishshop').setDescription('Open the cosmic fish shop.')
  ,new SlashCommandBuilder().setName('fishrod').setDescription('View or upgrade your fishing rod.')
  ,new SlashCommandBuilder().setName('fishstatuseffects').setDescription('View active fishing effects.')
  ,new SlashCommandBuilder().setName('fishdrink').setDescription('Drink a fishing buff.').addStringOption(o=>o.setName('item').setDescription('Buff drink').setRequired(true).addChoices({name:'Luck drink • 5 minutes',value:'luck_drink'},{name:'Value drink • 5 minutes',value:'value_drink'}))
  ,new SlashCommandBuilder().setName('fishmarket').setDescription('View the changing fish market.')
  ,new SlashCommandBuilder().setName('fishaquarium').setDescription('Open your personal fish aquarium.')
  ,new SlashCommandBuilder().setName('fishbattle').setDescription('Battle your equipped fish.')
  ,new SlashCommandBuilder().setName('fishbattlepvp').setDescription('Challenge another fisher.').addUserOption(o=>o.setName('user').setDescription('Opponent').setRequired(true))
].map(c=>c.toJSON());
export async function handleCommand(interaction) {
  await ensureGuild(interaction.guildId);
  const name=interaction.commandName;
  const adminOnly=['economy-add','logs','confession-setup','fish-setup','warn','warnings','kick','ban','timeout','purge','lock','unlock','unban','untimeout'];
  if(adminOnly.includes(name) && !interaction.memberPermissions?.has(PermissionFlagsBits.Administrator)) return interaction.reply({content:'🛡️ Only server administrators can use this command.',ephemeral:true});
  if(name==='ping') return interaction.reply({embeds:[yEmbed('☾ Yachiyo is watching over this server.','✦ The moonlit command center is online and watching this server.',YACHIYO_BLUE)]});
  if(name==='help') return interaction.reply({embeds:[new EmbedBuilder().setColor(0x8e7dff).setTitle('☾ YACHIYO COMMAND CENTER').setDescription('*The moonlit server manager is ready to assist.*').addFields({name:'✦ Economy',value:'`/balance`  `/daily`  `/work`  `/fish`\n`/pay`  `/deposit`  `/withdraw`  `/leaderboard`'},{name:'✦ Fishing',value:'`/fishinventory`  `/fishalmanac`\nUse the buttons on a catch card to explore your collection.'},{name:'✦ Moderation',value:'`/warn`  `/warnings`  `/kick`  `/ban`  `/timeout`\n`/untimeout`  `/unban`  `/purge`  `/lock`  `/unlock`  `/logs`'}).setFooter({text:'Yachiyo • Cosmic server manager'})]});
  if(name==='balance') { const user=interaction.options.getUser('user')??interaction.user; const b=await balance(user.id); return interaction.reply({embeds:[new EmbedBuilder().setColor(0xf0b6d8).setAuthor({name:'Yachiyo • Cosmic Treasury',iconURL:interaction.client.user.displayAvatarURL()}).setTitle('🌸 NYANKO_' + user.username.toUpperCase() + "'S BALANCE 🌸").setDescription('╭─────────────── ✦ ───────────────╮\\nHere is the current financial status of <@' + user.id + '>.\\n\\n💵 **Cash:** **' + b.wallet.toLocaleString() + '** coins\\n🏦 **Bank:** **' + b.bank.toLocaleString() + '** coins\\n✨ **Total:** **' + (b.wallet+b.bank).toLocaleString() + '** coins\\n╰─────────────── ✦ ───────────────╯').setFooter({text:'Global economy • shared across every server'})]}); }
  if(['daily','work'].includes(name)) { try { const r=await claim(interaction.user.id,name); return interaction.reply({embeds:[yEmbed(name==='daily'?'🌙 Daily Cosmic Allowance':'🛠️ Work Complete',`✦ You received **${r.amount.toLocaleString()}** global coins.\n\nYour fortune has been recorded across every server.`)]}); } catch(e) { return interaction.reply({content:`Yachiyo says: ${e.message}`,ephemeral:true}); } }
  if(name==='confession') {
    const modal=new ModalBuilder().setCustomId('confession_submit').setTitle('☾ Send a private confession');
    const input=new TextInputBuilder().setCustomId('confession_content').setLabel('What would you like to confess?').setStyle(TextInputStyle.Paragraph).setPlaceholder('Write your confession here...').setRequired(true).setMaxLength(1000);
    modal.addComponents(new ActionRowBuilder().addComponents(input));
    return interaction.showModal(modal);
  }
  if(name==='fish-setup') {
    const channel=interaction.options.getChannel('channel');
    await setFishChannel(interaction.guildId,channel.id);
    return interaction.reply({embeds:[new EmbedBuilder().setColor(0x4db8e8).setTitle('🎣 Celestial fishing grounds prepared').setDescription('Fishing is now restricted to <#'+channel.id+'>.\n\nThe Cast Again buttons will only work there too.')]});
  }
  if(name==='confession-setup') {
    const channel=interaction.options.getChannel('channel');
    await setConfessionChannel(interaction.guildId,channel.id);
    return interaction.reply({embeds:[new EmbedBuilder().setColor(0xf3a6c7).setTitle('💌 Confession chamber prepared').setDescription('Confessions will now be published in <#'+channel.id+'>.')]});
  }

  if(name==='fish') { const fishChannel=await getFishChannel(interaction.guildId); if(fishChannel && interaction.channelId!==fishChannel) return interaction.reply({content:'🎣 Fishing is only available in <#'+fishChannel+'>.',ephemeral:true}); const wait=await cooldownRemaining(interaction.user.id,'fish'); if(wait>0) return interaction.reply({content:`🎣 Please wait **${Math.ceil(wait/1000)} second(s)** before fishing again.`,ephemeral:true}); try { await interaction.deferReply(); const casting=new EmbedBuilder().setColor(0x4db8e8).setTitle('🎣 YACHIYO’S CELESTIAL FISHING').setDescription('╭ 𖦹 ˚｡⋆ Casting your line...\n╰──────────────\n`[████░░░░░░░░░░░░░░░░]`\n\n*The cosmic tide is moving.*'); await interaction.editReply({embeds:[casting]}); await new Promise(r=>setTimeout(r,900)); const bite=new EmbedBuilder().setColor(0x8e7dff).setTitle('🎣 A BITE!').setDescription('╭ 𖦹 ˚｡⋆ Something is pulling the line!\n╰──────────────\n`[████████████░░░░░░░░]`\n\n*Reeling in the unknown...*'); await interaction.editReply({embeds:[bite]}); await new Promise(r=>setTimeout(r,500)); const fish=rollFish(); const rarity=FISH_RARITIES[fish.rarity]; await runPullSequence(interaction,fish.rarity); await castFish(interaction.user.id); await saveFish(interaction.user.id,fish); const card=await createFishCard({fish,rarity,valueBonus:0,luckBonus:0}); const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('fish_again').setLabel('Cast Again').setEmoji('🎣').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('fish_almanac').setLabel('Fish Almanac').setEmoji('📖').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('fish_inventory').setLabel('Inventory').setEmoji('🎒').setStyle(ButtonStyle.Success)); return interaction.editReply({content:`🐟 **${interaction.user.displayName}** caught a ${fish.name}!`,files:[card],components:[row],embeds:[]}); } catch(e) { return interaction.editReply({content:`Yachiyo says: ${e.message}`,embeds:[],components:[]}); } }
  if(name==='fishinventory') { const rows=await fishInventory(interaction.user.id); return interaction.reply({embeds:[new EmbedBuilder().setColor(0x4db8e8).setAuthor({name:'Yachiyo • Celestial Waters',iconURL:interaction.client.user.displayAvatarURL()}).setTitle('🌊 '+interaction.user.username+'’s Aquarium 𓆝').setDescription('────────── 𓆝 ⋆｡°✩ ──────────\\n' + (rows.length?rows.map((x,i)=>'**'+(i+1)+'. '+(FISH_RARITIES[x.rarity]?.label||x.rarity)+'**  •  '+x.fish_name+'  ×'+x.quantity).join('\n'):'*The aquarium is empty. Cast `/fish` to discover the tide.*') + '\\n────────── 𓆝 ⋆｡°✩ ──────────').setFooter({text:'Use the catch-card buttons to explore your collection.'})]}); }
  if(name==='fishalmanac') {
    const rows=await fishAlmanac(interaction.user.id);
    const order=['common','uncommon','rare','epic','legendary','mythic','ancient','celestial','secret','tsukuyomi'];
    const byRarity=new Map(rows.map(row=>[row.rarity,row]));
    const sections=order.filter(rarity=>byRarity.has(rarity)).map(rarity=>{
      const row=byRarity.get(rarity);
      const label=FISH_RARITIES[rarity]?.label||rarity;
      return '**'+label+' Collection:** '+row.discovered+' discovered  •  '+row.caught+' caught';
    });
    const body=sections.length?sections.join(String.fromCharCode(10)+String.fromCharCode(10)):'*No discoveries yet. The tide is waiting for your first cast.*';
    const description=['╭─────────────── 𓆝 ───────────────╮',body,'╰─────────────── 𓆝 ───────────────╯'].join(String.fromCharCode(10));
    return interaction.reply({embeds:[new EmbedBuilder().setColor(0x8e7dff).setAuthor({name:'Yachiyo • Celestial Almanac',iconURL:interaction.client.user.displayAvatarURL()}).setTitle('📖 ✧ CELESTIAL ALMANAC ✧').setDescription(description).setFooter({text:'Every discovery is recorded in Yachiyo’s cosmic archive.'})]});
  }
    if(name==='give') { try { await transfer(interaction.user.id,interaction.options.getUser('user').id,interaction.options.getInteger('amount')); return interaction.reply({embeds:[yEmbed('🎁 Cosmic Gift Delivered',`<@${interaction.options.getUser('user').id}> received **${interaction.options.getInteger('amount').toLocaleString()}** global coins.`)]}); } catch(e) { return interaction.reply({content:e.message,ephemeral:true}); } }
  if(name==='gamble') { const amount=interaction.options.getInteger('amount'); const multiplier=Number(interaction.options.getString('multiplier')||'2'); const tiers={1.5:{chance:.65,label:'SAFE'},2:{chance:.45,label:'BALANCED'},3:{chance:.25,label:'RISKY'}}; const tier=tiers[multiplier]||tiers[2]; if(amount<1) return interaction.reply({content:'Amount must be positive.',ephemeral:true}); try { const b=await balance(interaction.user.id); if(b.wallet<amount) throw new Error('Insufficient wallet funds.'); const won=Math.random()<tier.chance; const reward=Math.floor(amount*multiplier); await addMoney(interaction.user.id,won?reward:-amount,'gamble'); const after=await balance(interaction.user.id); return interaction.reply({embeds:[new EmbedBuilder().setColor(won?0x42d392:0xe05b67).setTitle('🎲 GAMBLE • x'+multiplier+' 🎲').setDescription(won?'You rolled the dice... and **WON!**':'You rolled the dice... and **LOST!**').addFields({name:'🎲 Wager',value:'**'+amount.toLocaleString()+'** coins',inline:true},{name:won?'💎 Reward':'🌊 Lost',value:'**'+(won?reward:amount).toLocaleString()+'** coins',inline:true},{name:'🍀 Luck Tier',value:'**'+tier.label+'** • '+Math.round(tier.chance*100)+'% chance',inline:true},{name:'💰 New Cash',value:'**'+after.wallet.toLocaleString()+'** coins',inline:false}).setFooter({text:'Higher multipliers bring greater rewards—and slimmer chances.'})]}); } catch(e) { return interaction.reply({content:e.message,ephemeral:true}); } }
  if(name==='rob') { const target=interaction.options.getUser('user'); if(target.id===interaction.user.id) return interaction.reply({content:'You cannot target yourself.',ephemeral:true}); try { const victim=await balance(target.id); const amount=Math.min(victim.wallet,Math.max(25,Math.floor(victim.wallet*.1))); if(amount<25) throw new Error('That user has too little wallet cash to rob.'); const success=Math.random()<.4; if(success) { await addMoney(target.id,-amount,'robbed'); await addMoney(interaction.user.id,amount,'rob'); } return interaction.reply({embeds:[new EmbedBuilder().setColor(success?0xffc857:0xe05b67).setTitle(success?'🕶️ SHADOW HEIST SUCCESS':'🚨 HEIST FOILED').setDescription(success?`You stole **${amount.toLocaleString()}** coins from <@${target.id}>.`:`The cosmic guard caught you before you could escape.`)]}); } catch(e) { return interaction.reply({content:e.message,ephemeral:true}); } }
  if(name==='fishprofile') { const user=interaction.options.getUser('user')||interaction.user; const b=await balance(user.id); const catches=await fishAlmanac(user.id); const total=catches.reduce((n,x)=>n+x.caught,0); return interaction.reply({embeds:[new EmbedBuilder().setColor(0x4db8e8).setAuthor({name:user.displayName,iconURL:user.displayAvatarURL()}).setTitle('🎣 CELESTIAL FISHER PROFILE').setDescription(`**Total Catches:** ${total}\n**Unique Discoveries:** ${catches.reduce((n,x)=>n+x.discovered,0)}\n**Global Coins:** ${b.wallet.toLocaleString()}`)]}); }
  if(name==='fishleaderboard') { const rows=await leaderboard(10); return interaction.reply({embeds:[new EmbedBuilder().setColor(0x4db8e8).setTitle('🏆 GLOBAL FISHER LEADERBOARD').setDescription(rows.map((x,i)=>`${i+1}. <@${x.user_id}> — **${Number(x.total).toLocaleString()}** coins`).join('\n')||'No fishers yet.') ]}); }
  if(name==='fishrod') {
    try {
      const rod=await getRod(interaction.user.id);
      const next=rod.level<5?rod.tier.level+1:null;
      const nextTier=next?[{level:2,name:'Pearl Rod',cost:2500,luck:5,value:5},{level:3,name:'Starlace Rod',cost:10000,luck:10,value:12},{level:4,name:'Celestial Ribbon',cost:35000,luck:18,value:22},{level:5,name:'Tsukuyomi Thread',cost:100000,luck:30,value:40}].find(x=>x.level===next):null;
      return interaction.reply({embeds:[new EmbedBuilder().setColor(0xf3a6c7).setTitle('🎣 '+rod.tier.name).setDescription('Your fishing rod grows with every cosmic catch.').addFields({name:'✦ Level',value:'**'+rod.level+' / 5**',inline:true},{name:'🍀 Luck',value:'+'+rod.tier.luck+'%',inline:true},{name:'💎 Value',value:'+'+rod.tier.value+'%',inline:true},{name:'Next evolution',value:nextTier?'**'+nextTier.name+'** • '+nextTier.cost.toLocaleString()+' coins':'**Maximum tier reached**'}).setFooter({text:'Use /fishrod again after earning enough coins to upgrade.'})]});
    } catch(e) { return interaction.reply({content:e.message,ephemeral:true}); }
  }
  if(name==='fishstatuseffects') {
    const effects=await getActiveEffects(interaction.user.id);
    return interaction.reply({embeds:[new EmbedBuilder().setColor(0x8e7dff).setTitle('🧪 Active Tide Effects').setDescription(effects.length?effects.map(x=>'**'+x.item_id+'** • '+Math.max(0,x.seconds_left)+'s remaining').join('\\n'):'*No active effects. The tide is calm.*')]});
  }
  if(name==='fishdrink') {
    try { const effects=await drinkItem(interaction.user.id,interaction.options.getString('item')); return interaction.reply({embeds:[yEmbed('🧪 Buff activated', 'Your fishing drink is now flowing through the cosmic reel.\\n\\n'+effects.map(x=>'**'+x.item_id+'** • '+x.seconds_left+'s remaining').join('\\n'),0xf3a6c7)]}); }
    catch(e) { return interaction.reply({content:e.message,ephemeral:true}); }
  }
  if(['fishshop','fishmarket','fishaquarium','fishbattle','fishbattlepvp'].includes(name)) return interaction.reply({embeds:[new EmbedBuilder().setColor(0x8e7dff).setTitle('☾ '+name.toUpperCase()).setDescription('This enhanced interface is now registered. Its interactive shop, aquarium, battle, and market panels are being connected to your global fishing data.') ]});
  if(name==='economy-add') { const b=await addMoney(interaction.options.getUser('user').id,interaction.options.getInteger('amount'),'admin'); return interaction.reply(`Added coins. New wallet: **${b.wallet.toLocaleString()}**.`); }
  if(name==='logs') { const channel=interaction.options.getChannel('channel'); await setLogChannel(interaction.guildId,channel.id); return interaction.reply({embeds:[yEmbed('🛡️ Audit Watch Activated',`Yachiyo will now send structured audit records to <#${channel.id}>.`)]}); }
  if(['warn','kick','ban','timeout'].includes(name)) { const user=interaction.options.getUser('user'); const reason=interaction.options.getString('reason')||'No reason provided'; const member=await interaction.guild.members.fetch(user.id).catch(()=>null); if(!member) return interaction.reply({content:'That member is not in this server.',ephemeral:true}); try { let duration=null; if(name==='warn') await warn(interaction.guildId,user.id,interaction.user.id,reason); if(name==='kick') { await member.kick(reason); await createCase({guildId:interaction.guildId,targetId:user.id,moderatorId:interaction.user.id,action:'kick',reason}); } if(name==='ban') { await member.ban({reason}); await createCase({guildId:interaction.guildId,targetId:user.id,moderatorId:interaction.user.id,action:'ban',reason}); } if(name==='timeout') { const minutes=interaction.options.getInteger('minutes'); if(minutes<1||minutes>40320) return interaction.reply({content:'Minutes must be between 1 and 40,320.',ephemeral:true}); duration=minutes*60; await member.timeout(minutes*60000,reason); await createCase({guildId:interaction.guildId,targetId:user.id,moderatorId:interaction.user.id,action:'timeout',reason,durationSeconds:duration}); } await sendAuditLog(interaction.client,interaction.guild,{eventType:'moderation.action',actorId:interaction.user.id,targetId:user.id,data:{summary:'Yachiyo completed a '+name+' action.',reason}}); return interaction.reply({embeds:[yEmbed('🛡️ Moderation Action Complete',`Action: **${name}**\nMember: <@${user.id}>\nReason: ${reason}\n\n✦ This action has been recorded in the moderation case log.`)]}); } catch(e) { return interaction.reply({content:`I could not complete that action: ${e.message}`,ephemeral:true}); } }
  if(name==='warnings') { const rows=await recentCases(interaction.guildId,interaction.options.getUser('user').id); return interaction.reply({embeds:[new EmbedBuilder().setColor(0xffc857).setTitle('Moderation Cases').setDescription(rows.length?rows.map(x=>`#${x.id} • **${x.action}** • ${x.reason}`).join('\n'):'No cases found.')]}); }
  if(name==='purge') { const amount=interaction.options.getInteger('amount'); if(amount<1||amount>100) return interaction.reply({content:'Amount must be 1–100.',ephemeral:true}); const deleted=await interaction.channel.bulkDelete(amount,true); await createCase({guildId:interaction.guildId,targetId:interaction.user.id,moderatorId:interaction.user.id,action:'purge',reason:`Deleted ${deleted.size} messages`}); return interaction.reply({embeds:[yEmbed('🧹 Channel Cleared',`Yachiyo removed **${deleted.size}** messages from this channel.`,0xe67e22)],ephemeral:true}); }
  if(name==='pay') { try { await transfer(interaction.user.id,interaction.options.getUser('user').id,interaction.options.getInteger('amount')); return interaction.reply({embeds:[yEmbed('💫 Transfer Complete','Your global coin transfer crossed the cosmic tide safely.')]}); } catch(e) { return interaction.reply({content:e.message,ephemeral:true}); } }
  if(['deposit','withdraw'].includes(name)) { try { const b=await bankMove(interaction.user.id,interaction.options.getInteger('amount'),name); return interaction.reply({embeds:[yEmbed(name==='deposit'?'🏦 Deposit Complete':'💳 Withdrawal Complete',`Wallet: **${b.wallet.toLocaleString()}** coins\nBank: **${b.bank.toLocaleString()}** coins`)]}); } catch(e) { return interaction.reply({content:e.message,ephemeral:true}); } }
  if(name==='leaderboard') { const rows=await leaderboard(); return interaction.reply({embeds:[new EmbedBuilder().setColor(0x8e7dff).setTitle('☾ Global Cosmic Leaderboard').setDescription(rows.map((x,i)=>`${i+1}. <@${x.user_id}> — **${Number(x.total).toLocaleString()}** coins`).join('\n')||'No accounts yet.')]}); }
  if(name==='lock'||name==='unlock') { await interaction.channel.permissionOverwrites.edit(interaction.guild.roles.everyone,{SendMessages:name==='unlock'}); await createCase({guildId:interaction.guildId,targetId:interaction.channelId,moderatorId:interaction.user.id,action:name,reason:`Channel ${name}ed`}); return interaction.reply({embeds:[yEmbed(name==='lock'?'🔒 Channel Sealed':'🔓 Channel Opened',`This channel has been ${name}ed by Yachiyo.`,0xe67e22)]}); }
  if(name==='unban') { const id=interaction.options.getString('user_id'); await interaction.guild.members.unban(id,interaction.options.getString('reason')||'No reason provided'); await createCase({guildId:interaction.guildId,targetId:id,moderatorId:interaction.user.id,action:'unban',reason:interaction.options.getString('reason')}); return interaction.reply({embeds:[yEmbed('🌙 Ban Lifted',`<@${id}> may now return to the server.`)]}); }
  if(name==='untimeout') { const user=interaction.options.getUser('user'); const member=await interaction.guild.members.fetch(user.id); await member.timeout(null,'Timeout removed'); await createCase({guildId:interaction.guildId,targetId:user.id,moderatorId:interaction.user.id,action:'untimeout',reason:'Timeout removed'}); return interaction.reply({embeds:[yEmbed('⏱️ Timeout Removed',`<@${user.id}> is no longer timed out.`)]}); }
}
